2025-04-23 21:59:21,097 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-23 21:59:21,097 INFO: Using device: cpu
2025-04-23 21:59:21,101 ERROR: Failed to load model checkpoint
Traceback (most recent call last):
  File "/Users/derekjrussell/Documents/repos/ConnectFourGame/ml_service/ml_service.py", line 56, in <module>
    checkpoint = torch.load(paths["ckpt"], map_location=device)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt'
2025-04-23 22:00:23,045 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-23 22:00:23,046 INFO: Using device: cpu
2025-04-23 22:00:23,059 ERROR: Failed to load model checkpoint
Traceback (most recent call last):
  File "/Users/derekjrussell/Documents/repos/ConnectFourGame/ml_service/ml_service.py", line 56, in <module>
    checkpoint = torch.load(paths["ckpt"], map_location=device)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt'
2025-04-23 22:00:30,431 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-23 22:00:30,431 INFO: Using device: cpu
2025-04-23 22:00:30,434 ERROR: Failed to load model checkpoint
Traceback (most recent call last):
  File "/Users/derekjrussell/Documents/repos/ConnectFourGame/ml_service/ml_service.py", line 56, in <module>
    checkpoint = torch.load(paths["ckpt"], map_location=device)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt'
2025-04-23 22:08:59,944 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-23 22:08:59,945 INFO: Using device: cpu
2025-04-23 22:08:59,948 ERROR: Failed to load model checkpoint
Traceback (most recent call last):
  File "/Users/derekjrussell/Documents/repos/ConnectFourGame/ml_service/ml_service.py", line 56, in <module>
    checkpoint = torch.load(paths["ckpt"], map_location=device)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt'
2025-04-23 22:09:13,440 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-23 22:09:13,440 INFO: Using device: cpu
2025-04-23 22:09:13,444 ERROR: Failed to load model checkpoint
Traceback (most recent call last):
  File "/Users/derekjrussell/Documents/repos/ConnectFourGame/ml_service/ml_service.py", line 56, in <module>
    checkpoint = torch.load(paths["ckpt"], map_location=device)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt'
2025-04-23 22:09:29,337 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-23 22:09:29,337 INFO: Using device: cpu
2025-04-23 22:09:29,341 ERROR: Failed to load model checkpoint
Traceback (most recent call last):
  File "/Users/derekjrussell/Documents/repos/ConnectFourGame/ml_service/ml_service.py", line 56, in <module>
    checkpoint = torch.load(paths["ckpt"], map_location=device)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt'
2025-04-23 22:09:30,875 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-23 22:09:30,875 INFO: Using device: cpu
2025-04-23 22:09:30,879 ERROR: Failed to load model checkpoint
Traceback (most recent call last):
  File "/Users/derekjrussell/Documents/repos/ConnectFourGame/ml_service/ml_service.py", line 56, in <module>
    checkpoint = torch.load(paths["ckpt"], map_location=device)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt'
2025-04-23 22:09:39,817 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-23 22:09:39,817 INFO: Using device: cpu
2025-04-23 22:09:39,820 ERROR: Failed to load model checkpoint
Traceback (most recent call last):
  File "/Users/derekjrussell/Documents/repos/ConnectFourGame/ml_service/ml_service.py", line 56, in <module>
    checkpoint = torch.load(paths["ckpt"], map_location=device)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt'
2025-04-23 22:09:54,396 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-23 22:09:54,397 INFO: Using device: cpu
2025-04-23 22:09:54,400 ERROR: Failed to load model checkpoint
Traceback (most recent call last):
  File "/Users/derekjrussell/Documents/repos/ConnectFourGame/ml_service/ml_service.py", line 56, in <module>
    checkpoint = torch.load(paths["ckpt"], map_location=device)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt'
2025-04-23 22:09:55,879 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-23 22:09:55,879 INFO: Using device: cpu
2025-04-23 22:09:55,883 ERROR: Failed to load model checkpoint
Traceback (most recent call last):
  File "/Users/derekjrussell/Documents/repos/ConnectFourGame/ml_service/ml_service.py", line 56, in <module>
    checkpoint = torch.load(paths["ckpt"], map_location=device)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt'
2025-04-23 22:10:21,018 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-23 22:10:21,019 INFO: Using device: cpu
2025-04-23 22:10:21,023 ERROR: Failed to load model checkpoint
Traceback (most recent call last):
  File "/Users/derekjrussell/Documents/repos/ConnectFourGame/ml_service/ml_service.py", line 56, in <module>
    checkpoint = torch.load(paths["ckpt"], map_location=device)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt'
2025-04-23 22:10:27,959 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-23 22:10:27,960 INFO: Using device: cpu
2025-04-23 22:10:27,964 ERROR: Failed to load model checkpoint
Traceback (most recent call last):
  File "/Users/derekjrussell/Documents/repos/ConnectFourGame/ml_service/ml_service.py", line 56, in <module>
    checkpoint = torch.load(paths["ckpt"], map_location=device)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt'
2025-04-23 22:10:30,600 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-23 22:10:30,600 INFO: Using device: cpu
2025-04-23 22:10:30,603 ERROR: Failed to load model checkpoint
Traceback (most recent call last):
  File "/Users/derekjrussell/Documents/repos/ConnectFourGame/ml_service/ml_service.py", line 56, in <module>
    checkpoint = torch.load(paths["ckpt"], map_location=device)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt'
2025-04-23 22:10:34,808 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-23 22:10:34,808 INFO: Using device: cpu
2025-04-23 22:10:34,811 ERROR: Failed to load model checkpoint
Traceback (most recent call last):
  File "/Users/derekjrussell/Documents/repos/ConnectFourGame/ml_service/ml_service.py", line 56, in <module>
    checkpoint = torch.load(paths["ckpt"], map_location=device)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt'
2025-04-23 22:10:47,301 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-23 22:10:47,301 INFO: Using device: cpu
2025-04-23 22:10:47,305 ERROR: Failed to load model checkpoint
Traceback (most recent call last):
  File "/Users/derekjrussell/Documents/repos/ConnectFourGame/ml_service/ml_service.py", line 56, in <module>
    checkpoint = torch.load(paths["ckpt"], map_location=device)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt'
2025-04-23 22:10:49,205 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-23 22:10:49,205 INFO: Using device: cpu
2025-04-23 22:10:49,209 ERROR: Failed to load model checkpoint
Traceback (most recent call last):
  File "/Users/derekjrussell/Documents/repos/ConnectFourGame/ml_service/ml_service.py", line 56, in <module>
    checkpoint = torch.load(paths["ckpt"], map_location=device)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt'
2025-04-23 22:10:55,298 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-23 22:10:55,299 INFO: Using device: cpu
2025-04-23 22:10:55,302 ERROR: Failed to load model checkpoint
Traceback (most recent call last):
  File "/Users/derekjrussell/Documents/repos/ConnectFourGame/ml_service/ml_service.py", line 56, in <module>
    checkpoint = torch.load(paths["ckpt"], map_location=device)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt'
2025-04-23 22:11:05,284 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-23 22:11:05,285 INFO: Using device: cpu
2025-04-23 22:11:05,289 ERROR: Failed to load model checkpoint
Traceback (most recent call last):
  File "/Users/derekjrussell/Documents/repos/ConnectFourGame/ml_service/ml_service.py", line 56, in <module>
    checkpoint = torch.load(paths["ckpt"], map_location=device)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt'
2025-04-23 22:11:08,436 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-23 22:11:08,436 INFO: Using device: cpu
2025-04-23 22:11:08,441 ERROR: Failed to load model checkpoint
Traceback (most recent call last):
  File "/Users/derekjrussell/Documents/repos/ConnectFourGame/ml_service/ml_service.py", line 56, in <module>
    checkpoint = torch.load(paths["ckpt"], map_location=device)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt'
2025-04-23 22:11:14,561 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-23 22:11:14,562 INFO: Using device: cpu
2025-04-23 22:11:14,566 ERROR: Failed to load model checkpoint
Traceback (most recent call last):
  File "/Users/derekjrussell/Documents/repos/ConnectFourGame/ml_service/ml_service.py", line 56, in <module>
    checkpoint = torch.load(paths["ckpt"], map_location=device)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt'
2025-04-23 22:11:16,803 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-23 22:11:16,803 INFO: Using device: cpu
2025-04-23 22:11:16,807 ERROR: Failed to load model checkpoint
Traceback (most recent call last):
  File "/Users/derekjrussell/Documents/repos/ConnectFourGame/ml_service/ml_service.py", line 56, in <module>
    checkpoint = torch.load(paths["ckpt"], map_location=device)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt'
2025-04-23 22:11:29,030 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-23 22:11:29,031 INFO: Using device: cpu
2025-04-23 22:11:29,034 ERROR: Failed to load model checkpoint
Traceback (most recent call last):
  File "/Users/derekjrussell/Documents/repos/ConnectFourGame/ml_service/ml_service.py", line 56, in <module>
    checkpoint = torch.load(paths["ckpt"], map_location=device)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt'
2025-04-23 22:11:30,729 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-23 22:11:30,729 INFO: Using device: cpu
2025-04-23 22:11:30,733 ERROR: Failed to load model checkpoint
Traceback (most recent call last):
  File "/Users/derekjrussell/Documents/repos/ConnectFourGame/ml_service/ml_service.py", line 56, in <module>
    checkpoint = torch.load(paths["ckpt"], map_location=device)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt'
2025-04-23 22:11:35,931 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-23 22:11:35,932 INFO: Using device: cpu
2025-04-23 22:11:35,935 ERROR: Failed to load model checkpoint
Traceback (most recent call last):
  File "/Users/derekjrussell/Documents/repos/ConnectFourGame/ml_service/ml_service.py", line 56, in <module>
    checkpoint = torch.load(paths["ckpt"], map_location=device)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt'
2025-04-23 22:11:44,921 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-23 22:11:44,923 INFO: Using device: cpu
2025-04-23 22:11:44,926 ERROR: Failed to load model checkpoint
Traceback (most recent call last):
  File "/Users/derekjrussell/Documents/repos/ConnectFourGame/ml_service/ml_service.py", line 56, in <module>
    checkpoint = torch.load(paths["ckpt"], map_location=device)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt'
2025-04-23 22:11:56,284 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-23 22:11:56,284 INFO: Using device: cpu
2025-04-23 22:11:56,288 ERROR: Failed to load model checkpoint
Traceback (most recent call last):
  File "/Users/derekjrussell/Documents/repos/ConnectFourGame/ml_service/ml_service.py", line 56, in <module>
    checkpoint = torch.load(paths["ckpt"], map_location=device)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt'
2025-04-23 22:11:57,786 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-23 22:11:57,786 INFO: Using device: cpu
2025-04-23 22:11:57,789 ERROR: Failed to load model checkpoint
Traceback (most recent call last):
  File "/Users/derekjrussell/Documents/repos/ConnectFourGame/ml_service/ml_service.py", line 56, in <module>
    checkpoint = torch.load(paths["ckpt"], map_location=device)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt'
2025-04-23 22:12:01,208 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-23 22:12:01,208 INFO: Using device: cpu
2025-04-23 22:12:01,212 ERROR: Failed to load model checkpoint
Traceback (most recent call last):
  File "/Users/derekjrussell/Documents/repos/ConnectFourGame/ml_service/ml_service.py", line 56, in <module>
    checkpoint = torch.load(paths["ckpt"], map_location=device)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt'
2025-04-23 22:12:07,704 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-23 22:12:07,704 INFO: Using device: cpu
2025-04-23 22:12:07,708 ERROR: Failed to load model checkpoint
Traceback (most recent call last):
  File "/Users/derekjrussell/Documents/repos/ConnectFourGame/ml_service/ml_service.py", line 56, in <module>
    checkpoint = torch.load(paths["ckpt"], map_location=device)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt'
2025-04-23 22:12:09,096 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-23 22:12:09,097 INFO: Using device: cpu
2025-04-23 22:12:09,100 ERROR: Failed to load model checkpoint
Traceback (most recent call last):
  File "/Users/derekjrussell/Documents/repos/ConnectFourGame/ml_service/ml_service.py", line 56, in <module>
    checkpoint = torch.load(paths["ckpt"], map_location=device)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt'
2025-04-23 22:12:16,057 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-23 22:12:16,057 INFO: Using device: cpu
2025-04-23 22:12:16,061 ERROR: Failed to load model checkpoint
Traceback (most recent call last):
  File "/Users/derekjrussell/Documents/repos/ConnectFourGame/ml_service/ml_service.py", line 56, in <module>
    checkpoint = torch.load(paths["ckpt"], map_location=device)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt'
2025-04-23 22:12:22,751 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-23 22:12:22,752 INFO: Using device: cpu
2025-04-23 22:12:22,756 ERROR: Failed to load model checkpoint
Traceback (most recent call last):
  File "/Users/derekjrussell/Documents/repos/ConnectFourGame/ml_service/ml_service.py", line 56, in <module>
    checkpoint = torch.load(paths["ckpt"], map_location=device)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt'
2025-04-23 22:12:25,540 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-23 22:12:25,541 INFO: Using device: cpu
2025-04-23 22:12:25,544 ERROR: Failed to load model checkpoint
Traceback (most recent call last):
  File "/Users/derekjrussell/Documents/repos/ConnectFourGame/ml_service/ml_service.py", line 56, in <module>
    checkpoint = torch.load(paths["ckpt"], map_location=device)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt'
2025-04-23 22:12:30,759 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-23 22:12:30,760 INFO: Using device: cpu
2025-04-23 22:12:30,763 ERROR: Failed to load model checkpoint
Traceback (most recent call last):
  File "/Users/derekjrussell/Documents/repos/ConnectFourGame/ml_service/ml_service.py", line 56, in <module>
    checkpoint = torch.load(paths["ckpt"], map_location=device)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt'
2025-04-23 22:12:32,501 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-23 22:12:32,501 INFO: Using device: cpu
2025-04-23 22:12:32,505 ERROR: Failed to load model checkpoint
Traceback (most recent call last):
  File "/Users/derekjrussell/Documents/repos/ConnectFourGame/ml_service/ml_service.py", line 56, in <module>
    checkpoint = torch.load(paths["ckpt"], map_location=device)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt'
2025-04-23 22:12:38,247 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-23 22:12:38,248 INFO: Using device: cpu
2025-04-23 22:12:38,251 ERROR: Failed to load model checkpoint
Traceback (most recent call last):
  File "/Users/derekjrussell/Documents/repos/ConnectFourGame/ml_service/ml_service.py", line 56, in <module>
    checkpoint = torch.load(paths["ckpt"], map_location=device)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt'
2025-04-23 22:12:42,958 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-23 22:12:42,958 INFO: Using device: cpu
2025-04-23 22:12:42,962 ERROR: Failed to load model checkpoint
Traceback (most recent call last):
  File "/Users/derekjrussell/Documents/repos/ConnectFourGame/ml_service/ml_service.py", line 56, in <module>
    checkpoint = torch.load(paths["ckpt"], map_location=device)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt'
2025-04-23 22:12:46,396 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-23 22:12:46,397 INFO: Using device: cpu
2025-04-23 22:12:46,401 ERROR: Failed to load model checkpoint
Traceback (most recent call last):
  File "/Users/derekjrussell/Documents/repos/ConnectFourGame/ml_service/ml_service.py", line 56, in <module>
    checkpoint = torch.load(paths["ckpt"], map_location=device)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt'
2025-04-23 22:12:52,354 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-23 22:12:52,355 INFO: Using device: cpu
2025-04-23 22:12:52,358 ERROR: Failed to load model checkpoint
Traceback (most recent call last):
  File "/Users/derekjrussell/Documents/repos/ConnectFourGame/ml_service/ml_service.py", line 56, in <module>
    checkpoint = torch.load(paths["ckpt"], map_location=device)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt'
2025-04-23 22:13:59,904 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-23 22:13:59,905 INFO: Using device: cpu
2025-04-23 22:13:59,908 ERROR: Failed to load model checkpoint
Traceback (most recent call last):
  File "/Users/derekjrussell/Documents/repos/ConnectFourGame/ml_service/ml_service.py", line 56, in <module>
    checkpoint = torch.load(paths["ckpt"], map_location=device)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt'
2025-04-23 22:14:11,368 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-23 22:14:11,368 INFO: Using device: cpu
2025-04-23 22:14:11,372 ERROR: Failed to load model checkpoint
Traceback (most recent call last):
  File "/Users/derekjrussell/Documents/repos/ConnectFourGame/ml_service/ml_service.py", line 56, in <module>
    checkpoint = torch.load(paths["ckpt"], map_location=device)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt'
2025-04-23 22:14:12,980 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-23 22:14:12,980 INFO: Using device: cpu
2025-04-23 22:14:12,983 ERROR: Failed to load model checkpoint
Traceback (most recent call last):
  File "/Users/derekjrussell/Documents/repos/ConnectFourGame/ml_service/ml_service.py", line 56, in <module>
    checkpoint = torch.load(paths["ckpt"], map_location=device)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt'
2025-04-23 22:14:23,741 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-23 22:14:23,741 INFO: Using device: cpu
2025-04-23 22:14:23,745 ERROR: Failed to load model checkpoint
Traceback (most recent call last):
  File "/Users/derekjrussell/Documents/repos/ConnectFourGame/ml_service/ml_service.py", line 56, in <module>
    checkpoint = torch.load(paths["ckpt"], map_location=device)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt'
2025-04-23 22:14:26,470 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-23 22:14:26,470 INFO: Using device: cpu
2025-04-23 22:14:26,473 ERROR: Failed to load model checkpoint
Traceback (most recent call last):
  File "/Users/derekjrussell/Documents/repos/ConnectFourGame/ml_service/ml_service.py", line 56, in <module>
    checkpoint = torch.load(paths["ckpt"], map_location=device)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt'
2025-04-23 22:14:31,802 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-23 22:14:31,802 INFO: Using device: cpu
2025-04-23 22:14:31,806 ERROR: Failed to load model checkpoint
Traceback (most recent call last):
  File "/Users/derekjrussell/Documents/repos/ConnectFourGame/ml_service/ml_service.py", line 56, in <module>
    checkpoint = torch.load(paths["ckpt"], map_location=device)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt'
2025-04-23 22:14:36,707 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-23 22:14:36,707 INFO: Using device: cpu
2025-04-23 22:14:36,711 ERROR: Failed to load model checkpoint
Traceback (most recent call last):
  File "/Users/derekjrussell/Documents/repos/ConnectFourGame/ml_service/ml_service.py", line 56, in <module>
    checkpoint = torch.load(paths["ckpt"], map_location=device)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt'
2025-04-23 22:14:41,909 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-23 22:14:41,909 INFO: Using device: cpu
2025-04-23 22:14:41,913 ERROR: Failed to load model checkpoint
Traceback (most recent call last):
  File "/Users/derekjrussell/Documents/repos/ConnectFourGame/ml_service/ml_service.py", line 56, in <module>
    checkpoint = torch.load(paths["ckpt"], map_location=device)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt'
2025-04-23 22:18:49,145 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-23 22:18:49,147 INFO: Using device: cpu
2025-04-23 22:18:49,150 ERROR: Failed to load model checkpoint
Traceback (most recent call last):
  File "/Users/derekjrussell/Documents/repos/ConnectFourGame/ml_service/ml_service.py", line 56, in <module>
    checkpoint = torch.load(paths["ckpt"], map_location=device)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt'
2025-04-23 22:19:03,405 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-23 22:19:03,406 INFO: Using device: cpu
2025-04-23 22:19:03,409 ERROR: Failed to load model checkpoint
Traceback (most recent call last):
  File "/Users/derekjrussell/Documents/repos/ConnectFourGame/ml_service/ml_service.py", line 56, in <module>
    checkpoint = torch.load(paths["ckpt"], map_location=device)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt'
2025-04-23 22:19:05,889 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-23 22:19:05,889 INFO: Using device: cpu
2025-04-23 22:19:05,892 ERROR: Failed to load model checkpoint
Traceback (most recent call last):
  File "/Users/derekjrussell/Documents/repos/ConnectFourGame/ml_service/ml_service.py", line 56, in <module>
    checkpoint = torch.load(paths["ckpt"], map_location=device)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt'
2025-04-23 22:19:50,805 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-23 22:19:50,805 INFO: Using device: cpu
2025-04-23 22:19:50,808 ERROR: Failed to load model checkpoint
Traceback (most recent call last):
  File "/Users/derekjrussell/Documents/repos/ConnectFourGame/ml_service/ml_service.py", line 56, in <module>
    checkpoint = torch.load(paths["ckpt"], map_location=device)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt'
2025-04-23 22:20:53,731 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-23 22:20:53,731 INFO: Using device: cpu
2025-04-23 22:20:53,735 ERROR: Failed to load model checkpoint
Traceback (most recent call last):
  File "/Users/derekjrussell/Documents/repos/ConnectFourGame/ml_service/ml_service.py", line 56, in <module>
    checkpoint = torch.load(paths["ckpt"], map_location=device)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt'
2025-04-23 22:21:53,405 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-23 22:21:53,406 INFO: Using device: cpu
2025-04-23 22:21:53,409 ERROR: Failed to load model checkpoint
Traceback (most recent call last):
  File "/Users/derekjrussell/Documents/repos/ConnectFourGame/ml_service/ml_service.py", line 56, in <module>
    checkpoint = torch.load(paths["ckpt"], map_location=device)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt'
2025-04-23 22:22:07,587 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-23 22:22:07,588 INFO: Using device: cpu
2025-04-23 22:22:07,591 ERROR: Failed to load model checkpoint
Traceback (most recent call last):
  File "/Users/derekjrussell/Documents/repos/ConnectFourGame/ml_service/ml_service.py", line 56, in <module>
    checkpoint = torch.load(paths["ckpt"], map_location=device)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt'
2025-04-23 22:23:24,724 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-23 22:23:24,725 INFO: Using device: cpu
2025-04-23 22:23:24,728 ERROR: Failed to load model checkpoint
Traceback (most recent call last):
  File "/Users/derekjrussell/Documents/repos/ConnectFourGame/ml_service/ml_service.py", line 56, in <module>
    checkpoint = torch.load(paths["ckpt"], map_location=device)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt'
2025-04-23 22:25:56,694 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-23 22:25:56,694 INFO: Using device: cpu
2025-04-23 22:25:56,698 ERROR: Failed to load model checkpoint
Traceback (most recent call last):
  File "/Users/derekjrussell/Documents/repos/ConnectFourGame/ml_service/ml_service.py", line 56, in <module>
    checkpoint = torch.load(paths["ckpt"], map_location=device)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt'
2025-04-23 22:26:16,377 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-23 22:26:16,377 INFO: Using device: cpu
2025-04-23 22:26:16,381 ERROR: Failed to load model checkpoint
Traceback (most recent call last):
  File "/Users/derekjrussell/Documents/repos/ConnectFourGame/ml_service/ml_service.py", line 56, in <module>
    checkpoint = torch.load(paths["ckpt"], map_location=device)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt'
2025-04-23 22:26:17,898 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-23 22:26:17,898 INFO: Using device: cpu
2025-04-23 22:26:17,902 ERROR: Failed to load model checkpoint
Traceback (most recent call last):
  File "/Users/derekjrussell/Documents/repos/ConnectFourGame/ml_service/ml_service.py", line 56, in <module>
    checkpoint = torch.load(paths["ckpt"], map_location=device)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt'
